{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "FlexGridLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "FlexGridLib-1.1.2.aar",
          "url": "FlexGridLib-1.1.2.aar",
          "size": 36446,
          "sha512": "8f11426c80c9e38cbe040429d3446dece3d3132a12565d67a99234f9b8c165ce1d769e3ee6928097d33ca609938f3b31196627863bed53b6c74a37bcb2b8bc45",
          "sha256": "b93099ed24d6b1947a80f062f5cdd5e26aae2718769a6ede1d848ad08b371182",
          "sha1": "8ac334b0fb009a0624f46226f9bf7c0ea8eb3f76",
          "md5": "ddcad05dc8bed467b05742eed6af90af"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "SmartGridLib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.simplecityapps",
          "module": "recyclerview-fastscroll",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "FlexGridLib-1.1.2.aar",
          "url": "FlexGridLib-1.1.2.aar",
          "size": 36446,
          "sha512": "8f11426c80c9e38cbe040429d3446dece3d3132a12565d67a99234f9b8c165ce1d769e3ee6928097d33ca609938f3b31196627863bed53b6c74a37bcb2b8bc45",
          "sha256": "b93099ed24d6b1947a80f062f5cdd5e26aae2718769a6ede1d848ad08b371182",
          "sha1": "8ac334b0fb009a0624f46226f9bf7c0ea8eb3f76",
          "md5": "ddcad05dc8bed467b05742eed6af90af"
        }
      ]
    }
  ]
}
