{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "BaiduMaps",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BaiduMaps-1.1.2.aar",
          "url": "BaiduMaps-1.1.2.aar",
          "size": 12639349,
          "sha512": "ba6a8d24f98ec13988c4cac6045725d0811405140e70f7af5eb367e2cf09f4d23fdf2d5cc41877646ca67cf97cba3c08d7651d6a5f124775b99543ee57515dd7",
          "sha256": "103f616a122a1a9ff65044753a551178b0638f7f55bf8557cc80bf894dd69015",
          "sha1": "56d0985f9d40e109d00438b8d41961c2a6e7e95d",
          "md5": "81295b77ac4ac88c0d0e903a3ac78f6d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "LocationLib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "BaiduMaps-1.1.2.aar",
          "url": "BaiduMaps-1.1.2.aar",
          "size": 12639349,
          "sha512": "ba6a8d24f98ec13988c4cac6045725d0811405140e70f7af5eb367e2cf09f4d23fdf2d5cc41877646ca67cf97cba3c08d7651d6a5f124775b99543ee57515dd7",
          "sha256": "103f616a122a1a9ff65044753a551178b0638f7f55bf8557cc80bf894dd69015",
          "sha1": "56d0985f9d40e109d00438b8d41961c2a6e7e95d",
          "md5": "81295b77ac4ac88c0d0e903a3ac78f6d"
        }
      ]
    }
  ]
}
