{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "SmartGridLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "SmartGridLib-1.1.2.aar",
          "url": "SmartGridLib-1.1.2.aar",
          "size": 46716,
          "sha512": "5168c454f97fe862f36377ee33a8c1476ec93ae6d3740264192885d677514e1ea9ea50a3757480ad1c848517a9c94cee49544962ec0e4007c664fb6ba39e7167",
          "sha256": "ae10f91fc3b6ea152b551cba56fa66e914d71d7a1447e29ce4cdc8f52a0bfaab",
          "sha1": "5e88c3058e7e2a9a8ae4fea2f3b3a03e162ef792",
          "md5": "67ea55f9e38a09151f54056ece33d3b3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.simplecityapps",
          "module": "recyclerview-fastscroll",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "SmartGridLib-1.1.2.aar",
          "url": "SmartGridLib-1.1.2.aar",
          "size": 46716,
          "sha512": "5168c454f97fe862f36377ee33a8c1476ec93ae6d3740264192885d677514e1ea9ea50a3757480ad1c848517a9c94cee49544962ec0e4007c664fb6ba39e7167",
          "sha256": "ae10f91fc3b6ea152b551cba56fa66e914d71d7a1447e29ce4cdc8f52a0bfaab",
          "sha1": "5e88c3058e7e2a9a8ae4fea2f3b3a03e162ef792",
          "md5": "67ea55f9e38a09151f54056ece33d3b3"
        }
      ]
    }
  ]
}
