{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "MobFoxAds",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MobFoxAds-1.1.2.aar",
          "url": "MobFoxAds-1.1.2.aar",
          "size": 622679,
          "sha512": "1b92122e2be29799e1f6c8e6f689ff7a9e25cff7846af37cba0406bcc9a1127cd876349e52f95293962e70fb1548d3577c7942b875e2025b9331e43e037ec193",
          "sha256": "0dea6a7af2dca90dc1c501fd6413af0155dbfd761234e84af0dd3f70964049cd",
          "sha1": "2db3bfe5a61aa996f0394de82781d154f03a4485",
          "md5": "957893b5d42b29eee74f44d9ecce3fff"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.simpleframework",
          "module": "simple-xml",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "stax",
              "module": "*"
            },
            {
              "group": "xpp3",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "MobFoxAds-1.1.2.aar",
          "url": "MobFoxAds-1.1.2.aar",
          "size": 622679,
          "sha512": "1b92122e2be29799e1f6c8e6f689ff7a9e25cff7846af37cba0406bcc9a1127cd876349e52f95293962e70fb1548d3577c7942b875e2025b9331e43e037ec193",
          "sha256": "0dea6a7af2dca90dc1c501fd6413af0155dbfd761234e84af0dd3f70964049cd",
          "sha1": "2db3bfe5a61aa996f0394de82781d154f03a4485",
          "md5": "957893b5d42b29eee74f44d9ecce3fff"
        }
      ]
    }
  ]
}
