{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "MediaRecorder",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MediaRecorder-1.1.2.aar",
          "url": "MediaRecorder-1.1.2.aar",
          "size": 29464,
          "sha512": "6814712213d57353e88aa377a3ce371ee63f5e9d51b729498acb4761b10c21e64b1038525e094e55ac14d16e51eb0de824706ef0c1df44f8618201a961aee20f",
          "sha256": "23bf3c12d1a9a07963447bdb4d415e2e22f76157ff3b7cb2c9cac6e653413d20",
          "sha1": "e9d6ef86f1d6931f7e9ad07f43c79205c95b3b9f",
          "md5": "39e75d0830f89265bd0da5a05ce105bb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "MediaRecorder-1.1.2.aar",
          "url": "MediaRecorder-1.1.2.aar",
          "size": 29464,
          "sha512": "6814712213d57353e88aa377a3ce371ee63f5e9d51b729498acb4761b10c21e64b1038525e094e55ac14d16e51eb0de824706ef0c1df44f8618201a961aee20f",
          "sha256": "23bf3c12d1a9a07963447bdb4d415e2e22f76157ff3b7cb2c9cac6e653413d20",
          "sha1": "e9d6ef86f1d6931f7e9ad07f43c79205c95b3b9f",
          "md5": "39e75d0830f89265bd0da5a05ce105bb"
        }
      ]
    }
  ]
}
