{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "OneSignalModule",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "OneSignalModule-1.1.2.aar",
          "url": "OneSignalModule-1.1.2.aar",
          "size": 31996,
          "sha512": "c32a8f48c2ec4f993eb5f09f5b4623bd1845669b4b23bc1221b285f6d9719737676a5a2d2ca5edb3fb36ef923d9c3a44c0dc6b58dbc6b47d787e12b62e2c1e15",
          "sha256": "32ae61f413db6f31a42cbd42eecc85db9261f1918a5e6af3e3afb82d9f6184de",
          "sha1": "fa76d5a6452b443d7b6e4a21a4436f5c4dadf2ab",
          "md5": "b9f41ac09547f60ccbdb952ed9368064"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.onesignal",
          "module": "OneSignal",
          "version": {
            "requires": "4.6.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "20.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "OneSignalModule-1.1.2.aar",
          "url": "OneSignalModule-1.1.2.aar",
          "size": 31996,
          "sha512": "c32a8f48c2ec4f993eb5f09f5b4623bd1845669b4b23bc1221b285f6d9719737676a5a2d2ca5edb3fb36ef923d9c3a44c0dc6b58dbc6b47d787e12b62e2c1e15",
          "sha256": "32ae61f413db6f31a42cbd42eecc85db9261f1918a5e6af3e3afb82d9f6184de",
          "sha1": "fa76d5a6452b443d7b6e4a21a4436f5c4dadf2ab",
          "md5": "b9f41ac09547f60ccbdb952ed9368064"
        }
      ]
    }
  ]
}
