{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "UnitTestingUtils",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UnitTestingUtils-1.1.2.aar",
          "url": "UnitTestingUtils-1.1.2.aar",
          "size": 23573,
          "sha512": "328b4988301889ce1f7d8f89cd5e5d3354d62e3d6d556b24e9f701ed5e92508ed7a5e4f76c75768f9fce574d11ab4a54ec25ee05eb06a35a4844a83f589e2866",
          "sha256": "e57088f17ef57e7198a1058e4c321abfc37044ce6471c7b99c988a0e1414c4cb",
          "sha1": "12c56b485a8168ac2e4d7e93f3529a893bce4d79",
          "md5": "47a673ed23e53ef2f86ed5f1ef6acbdb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "UnitTestingUtils-1.1.2.aar",
          "url": "UnitTestingUtils-1.1.2.aar",
          "size": 23573,
          "sha512": "328b4988301889ce1f7d8f89cd5e5d3354d62e3d6d556b24e9f701ed5e92508ed7a5e4f76c75768f9fce574d11ab4a54ec25ee05eb06a35a4844a83f589e2866",
          "sha256": "e57088f17ef57e7198a1058e4c321abfc37044ce6471c7b99c988a0e1414c4cb",
          "sha1": "12c56b485a8168ac2e4d7e93f3529a893bce4d79",
          "md5": "47a673ed23e53ef2f86ed5f1ef6acbdb"
        }
      ]
    }
  ]
}
