{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "RelativeTimerLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "RelativeTimerLib-1.1.2.aar",
          "url": "RelativeTimerLib-1.1.2.aar",
          "size": 38800,
          "sha512": "76335d7506faaa38cadbedc271bc7797d7c2bd2459f54174afe7e448b3e72aa54a864a2e9c0e5f4ac5e08f861529cfce4e27749404f5ae7b38a1f18c4e4d72b4",
          "sha256": "aa3037b98aecaf9157a4fa90816ae27bdf8754662f8a97ee541f64274530d47a",
          "sha1": "72fb4fabc243b59ddf2d2b725e2a86dd67d0282d",
          "md5": "1c2882a2fcfa06bbcb286173bc2b0c8d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "net.time4j",
          "module": "time4j-android",
          "version": {
            "requires": "4.4.3-2019c"
          }
        }
      ],
      "files": [
        {
          "name": "RelativeTimerLib-1.1.2.aar",
          "url": "RelativeTimerLib-1.1.2.aar",
          "size": 38800,
          "sha512": "76335d7506faaa38cadbedc271bc7797d7c2bd2459f54174afe7e448b3e72aa54a864a2e9c0e5f4ac5e08f861529cfce4e27749404f5ae7b38a1f18c4e4d72b4",
          "sha256": "aa3037b98aecaf9157a4fa90816ae27bdf8754662f8a97ee541f64274530d47a",
          "sha1": "72fb4fabc243b59ddf2d2b725e2a86dd67d0282d",
          "md5": "1c2882a2fcfa06bbcb286173bc2b0c8d"
        }
      ]
    }
  ]
}
