{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "UITestingLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "UITestingLib-1.1.2.aar",
          "url": "UITestingLib-1.1.2.aar",
          "size": 123934,
          "sha512": "3f684adc0f00f0f391bedf7bd536f0047aa8532a8f180721fa635ae5532dcdbcae33c3202482264599b58f283cfc717487f189007042f617445406a6b31c9035",
          "sha256": "598e409a46c10759d2361f2d6de7ea60dc0d77fed218716bd499aa0bbe4f8ea9",
          "sha1": "827ebf26b5dd1fd44cf0484106b3336dd3442ccb",
          "md5": "838d22945787ae316b69d85512fd357f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "CoreUserControls",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "UITestingLib-1.1.2.aar",
          "url": "UITestingLib-1.1.2.aar",
          "size": 123934,
          "sha512": "3f684adc0f00f0f391bedf7bd536f0047aa8532a8f180721fa635ae5532dcdbcae33c3202482264599b58f283cfc717487f189007042f617445406a6b31c9035",
          "sha256": "598e409a46c10759d2361f2d6de7ea60dc0d77fed218716bd499aa0bbe4f8ea9",
          "sha1": "827ebf26b5dd1fd44cf0484106b3336dd3442ccb",
          "md5": "838d22945787ae316b69d85512fd357f"
        }
      ]
    }
  ]
}
