{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "SqlDroidCipher",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "SqlDroidCipher-1.1.2.aar",
          "url": "SqlDroidCipher-1.1.2.aar",
          "size": 47082,
          "sha512": "c4c2c3a0eb7687f89ce3fce6be2d3dc462011d1f5e5164eb08bca1a585dc28e1afd0e7d72ef8d18486d7617ad48c78150ddb99028fe7633ad8122a86e4e99372",
          "sha256": "68d4d293a87ae6f30a0c0209d34e12fa440dc8a57a93ed2d9bc167e195c2455b",
          "sha1": "7f023c70ebb91b4f23b5dc9bdf28bbb291cc10a8",
          "md5": "87c02fa512a45176cadb59eefa682a47"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.zetetic",
          "module": "android-database-sqlcipher",
          "version": {
            "requires": "3.5.9"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "android-database-sqlcipher",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "SqlDroidCipher-1.1.2.aar",
          "url": "SqlDroidCipher-1.1.2.aar",
          "size": 47082,
          "sha512": "c4c2c3a0eb7687f89ce3fce6be2d3dc462011d1f5e5164eb08bca1a585dc28e1afd0e7d72ef8d18486d7617ad48c78150ddb99028fe7633ad8122a86e4e99372",
          "sha256": "68d4d293a87ae6f30a0c0209d34e12fa440dc8a57a93ed2d9bc167e195c2455b",
          "sha1": "7f023c70ebb91b4f23b5dc9bdf28bbb291cc10a8",
          "md5": "87c02fa512a45176cadb59eefa682a47"
        }
      ]
    }
  ]
}
