{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "FirebaseMessaging",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "FirebaseMessaging-1.1.2.aar",
          "url": "FirebaseMessaging-1.1.2.aar",
          "size": 28288,
          "sha512": "f799cdea666fc2e994b57bdc191719b3998612d606fd2eff193c83f068d2cc618865f833820b34f8b2f51b4a04cd187e1776039df82a416553cae0e3421fccec",
          "sha256": "d944eaedc69377498808ec585883e63a468e85c770291bcbf049081eb730f1ab",
          "sha1": "8c25fb89ac85b9bde2bbb14bf22a2bf01669b27b",
          "md5": "3cb9cbf4c98679518e2b6b90bc8c5d88"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "17.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "20.3.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "FirebaseMessaging-1.1.2.aar",
          "url": "FirebaseMessaging-1.1.2.aar",
          "size": 28288,
          "sha512": "f799cdea666fc2e994b57bdc191719b3998612d606fd2eff193c83f068d2cc618865f833820b34f8b2f51b4a04cd187e1776039df82a416553cae0e3421fccec",
          "sha256": "d944eaedc69377498808ec585883e63a468e85c770291bcbf049081eb730f1ab",
          "sha1": "8c25fb89ac85b9bde2bbb14bf22a2bf01669b27b",
          "md5": "3cb9cbf4c98679518e2b6b90bc8c5d88"
        }
      ]
    }
  ]
}
