{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "AdMobAds",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AdMobAds-1.1.2.aar",
          "url": "AdMobAds-1.1.2.aar",
          "size": 33786,
          "sha512": "a81148fb9332d1854775271b9edeba7104fcdc558ac925f298b4ba22588a03af562d2582a1c0d164b58c623f84d109489ea7d06c77d8c09849a466b4360ca4a1",
          "sha256": "47e4464829ba88460b73277722ea8c7811a0a68f642533d61b98c42fe30cf57c",
          "sha1": "3df098f0a3897ff5cc04698e5981077f4a16e4a1",
          "md5": "5fc2d9e6f1039b71502a23ec6deabadd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "AdsLib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "19.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "AdMobAds-1.1.2.aar",
          "url": "AdMobAds-1.1.2.aar",
          "size": 33786,
          "sha512": "a81148fb9332d1854775271b9edeba7104fcdc558ac925f298b4ba22588a03af562d2582a1c0d164b58c623f84d109489ea7d06c77d8c09849a466b4360ca4a1",
          "sha256": "47e4464829ba88460b73277722ea8c7811a0a68f642533d61b98c42fe30cf57c",
          "sha1": "3df098f0a3897ff5cc04698e5981077f4a16e4a1",
          "md5": "5fc2d9e6f1039b71502a23ec6deabadd"
        }
      ]
    }
  ]
}
