{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "spinner-library",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spinner-library-1.1.2.aar",
          "url": "spinner-library-1.1.2.aar",
          "size": 39588,
          "sha512": "724eb4f77f2d395a55f2790dc1dddcd7950831f290b7daf5aa6390f72a0e6952b9fac61bd694491ae8ec4a4f2675272fbf771f859ee3ae082db3342e06431e47",
          "sha256": "97fce9f25d065cb5072dfe1feb5bb376deb891affb43c95c32018f495311635e",
          "sha1": "56b707a17454616965d23eb3cb6c138308d8977b",
          "md5": "abce128e9798b5354266ee6bb78e1811"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spinner-library-1.1.2.aar",
          "url": "spinner-library-1.1.2.aar",
          "size": 39588,
          "sha512": "724eb4f77f2d395a55f2790dc1dddcd7950831f290b7daf5aa6390f72a0e6952b9fac61bd694491ae8ec4a4f2675272fbf771f859ee3ae082db3342e06431e47",
          "sha256": "97fce9f25d065cb5072dfe1feb5bb376deb891affb43c95c32018f495311635e",
          "sha1": "56b707a17454616965d23eb3cb6c138308d8977b",
          "md5": "abce128e9798b5354266ee6bb78e1811"
        }
      ]
    }
  ]
}
