{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "WebSocketsLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "WebSocketsLib-1.1.2.aar",
          "url": "WebSocketsLib-1.1.2.aar",
          "size": 44549,
          "sha512": "02054fb6e2f68c0f49670064218d4321ee5f1532b4622d5e0ca8e93303b3a6d73374ba9a0f600ee7e249b027fd865e4809e7af9bb5c43cea878914acdd745ff8",
          "sha256": "900a2e205ff52cb6797da70681ef5b4d44e8f5007e5b6d7310ebfe6b6d064c05",
          "sha1": "625b695760dbd0b5303be7cf3c799df73ec0bc41",
          "md5": "76b8bfd8d433a3bc997b071abbc14722"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-core-utils",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "WebSocketsLib-1.1.2.aar",
          "url": "WebSocketsLib-1.1.2.aar",
          "size": 44549,
          "sha512": "02054fb6e2f68c0f49670064218d4321ee5f1532b4622d5e0ca8e93303b3a6d73374ba9a0f600ee7e249b027fd865e4809e7af9bb5c43cea878914acdd745ff8",
          "sha256": "900a2e205ff52cb6797da70681ef5b4d44e8f5007e5b6d7310ebfe6b6d064c05",
          "sha1": "625b695760dbd0b5303be7cf3c799df73ec0bc41",
          "md5": "76b8bfd8d433a3bc997b071abbc14722"
        }
      ]
    }
  ]
}
