{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "ViewPagersLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ViewPagersLib-1.1.2.aar",
          "url": "ViewPagersLib-1.1.2.aar",
          "size": 119929,
          "sha512": "71970e5ac67cf6fb41acfc15567557f80c3b47fb93723f1d08c952666550af568b9e26c7288c8137b4b5cbe26bd6bd574ee85268ef5caab6204c4790f2e1ee26",
          "sha256": "0e5a814eff3bda61e2b680f5c4b15f3e43ba5b22474c3339843875012eeccbd0",
          "sha1": "be10ca870f9e79b8428c94a8502bd9401be637c5",
          "md5": "6d2aa1271afc1b31c0468a7a422300ca"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-core-ui",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ViewPagersLib-1.1.2.aar",
          "url": "ViewPagersLib-1.1.2.aar",
          "size": 119929,
          "sha512": "71970e5ac67cf6fb41acfc15567557f80c3b47fb93723f1d08c952666550af568b9e26c7288c8137b4b5cbe26bd6bd574ee85268ef5caab6204c4790f2e1ee26",
          "sha256": "0e5a814eff3bda61e2b680f5c4b15f3e43ba5b22474c3339843875012eeccbd0",
          "sha1": "be10ca870f9e79b8428c94a8502bd9401be637c5",
          "md5": "6d2aa1271afc1b31c0468a7a422300ca"
        }
      ]
    }
  ]
}
