{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "InAppBillingLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "InAppBillingLib-1.1.2.aar",
          "url": "InAppBillingLib-1.1.2.aar",
          "size": 63536,
          "sha512": "d45204094640e436cb2c588baf848536d5ad3d732214400389471df2209e42873905ce5c4cd7409035f30e502204d4ef1af94fcc4e6d8bbd76de1cee37a4fe48",
          "sha256": "758436b1e550b7e1eaa89ae394a74b26f92830928102fa58b5921e0240dd665e",
          "sha1": "6652cf3acce599e2f92b8e4b98d75675ce93c940",
          "md5": "075a0ad36306a47f8b673950784e7d80"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "InAppBillingLib-1.1.2.aar",
          "url": "InAppBillingLib-1.1.2.aar",
          "size": 63536,
          "sha512": "d45204094640e436cb2c588baf848536d5ad3d732214400389471df2209e42873905ce5c4cd7409035f30e502204d4ef1af94fcc4e6d8bbd76de1cee37a4fe48",
          "sha256": "758436b1e550b7e1eaa89ae394a74b26f92830928102fa58b5921e0240dd665e",
          "sha1": "6652cf3acce599e2f92b8e4b98d75675ce93c940",
          "md5": "075a0ad36306a47f8b673950784e7d80"
        }
      ]
    }
  ]
}
