{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "QRScanner",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "QRScanner-1.1.2.aar",
          "url": "QRScanner-1.1.2.aar",
          "size": 58885,
          "sha512": "84b23ad14a9ab768d67a5afed53b30cea8e031a4092a80d94fa6aa8353c8a24d8872e1bd1b06c9993fe14ed3208d6de5fe5e038ae5d0f01e96166d191058013c",
          "sha256": "c28ede1cc1a1cb215ec6967f9ede3524ca5c5c3d6e6584286537c5eafc1fec69",
          "sha1": "e63c5a0686121c8ea25b233acb8c46d4baba5351",
          "md5": "7ab795d9c1e1b70c72c2175c00675959"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.1"
          }
        },
        {
          "group": "io.fotoapparat",
          "module": "fotoapparat",
          "version": {
            "requires": "2.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "QRScanner-1.1.2.aar",
          "url": "QRScanner-1.1.2.aar",
          "size": 58885,
          "sha512": "84b23ad14a9ab768d67a5afed53b30cea8e031a4092a80d94fa6aa8353c8a24d8872e1bd1b06c9993fe14ed3208d6de5fe5e038ae5d0f01e96166d191058013c",
          "sha256": "c28ede1cc1a1cb215ec6967f9ede3524ca5c5c3d6e6584286537c5eafc1fec69",
          "sha1": "e63c5a0686121c8ea25b233acb8c46d4baba5351",
          "md5": "7ab795d9c1e1b70c72c2175c00675959"
        }
      ]
    }
  ]
}
