{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "GaodeMaps",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GaodeMaps-1.1.2.aar",
          "url": "GaodeMaps-1.1.2.aar",
          "size": 449287,
          "sha512": "f51e023f46f6819980d140cd1bc1dcd558a6750322cb1b400139b52147773d2019705a8c41e8371094e373777f676de079254133e662972d0e2319a4c27e3adc",
          "sha256": "eb55abc0c4fafa6ce40f9de61c02fcdc48eba93abd15332b03334c5f98208a04",
          "sha1": "da7c7fbe91d4506b5d7d35657afc900b05603575",
          "md5": "6e6f641c04ec84bd51299e5f92a7a8e4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "LocationLib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "GaodeMaps-1.1.2.aar",
          "url": "GaodeMaps-1.1.2.aar",
          "size": 449287,
          "sha512": "f51e023f46f6819980d140cd1bc1dcd558a6750322cb1b400139b52147773d2019705a8c41e8371094e373777f676de079254133e662972d0e2319a4c27e3adc",
          "sha256": "eb55abc0c4fafa6ce40f9de61c02fcdc48eba93abd15332b03334c5f98208a04",
          "sha1": "da7c7fbe91d4506b5d7d35657afc900b05603575",
          "md5": "6e6f641c04ec84bd51299e5f92a7a8e4"
        }
      ]
    }
  ]
}
