{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "JPush",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "JPush-1.1.2.aar",
          "url": "JPush-1.1.2.aar",
          "size": 31176,
          "sha512": "44a5e5672ac763d86f21e41b4b25c5819720dd7795eb783075174418ab896dc4562f62465370c55b37c643ec419e42c2a2eaf29c911b890f13b289a3ad558c86",
          "sha256": "83df0b02b711d3a89600cd1de900f4815c1cc665cdc92ecba4cb907d2edf6b3d",
          "sha1": "16a123ad8bc9f174e147041ce3aeb6f87bae93f6",
          "md5": "b0e85abbe0f156bbe459fdabff03c4cf"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "cn.jiguang.sdk",
          "module": "jpush",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "cn.jiguang.sdk",
          "module": "jcore",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "JPush-1.1.2.aar",
          "url": "JPush-1.1.2.aar",
          "size": 31176,
          "sha512": "44a5e5672ac763d86f21e41b4b25c5819720dd7795eb783075174418ab896dc4562f62465370c55b37c643ec419e42c2a2eaf29c911b890f13b289a3ad558c86",
          "sha256": "83df0b02b711d3a89600cd1de900f4815c1cc665cdc92ecba4cb907d2edf6b3d",
          "sha1": "16a123ad8bc9f174e147041ce3aeb6f87bae93f6",
          "md5": "b0e85abbe0f156bbe459fdabff03c4cf"
        }
      ]
    }
  ]
}
