{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "TwitterApi",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TwitterApi-1.1.2.aar",
          "url": "TwitterApi-1.1.2.aar",
          "size": 48230,
          "sha512": "9bc390b6bc707fb51b3d39b27225f9e3dcd2734459a9afa63b3da06d22a0607034bc54429807828c222e68e23f936973aa47ad23ae248ea15dca4ba1ac158e72",
          "sha256": "e8c18bf2b6b63e97a5a08933e2d6b0fc33d9994cea13923059e7e469f73b594c",
          "sha1": "07ff8e04f0e0ddf2bed7efb78f9c2ac997ead61d",
          "md5": "1cfa77eb65fa17b145500fca4330b193"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "TwitterApi-1.1.2.aar",
          "url": "TwitterApi-1.1.2.aar",
          "size": 48230,
          "sha512": "9bc390b6bc707fb51b3d39b27225f9e3dcd2734459a9afa63b3da06d22a0607034bc54429807828c222e68e23f936973aa47ad23ae248ea15dca4ba1ac158e72",
          "sha256": "e8c18bf2b6b63e97a5a08933e2d6b0fc33d9994cea13923059e7e469f73b594c",
          "sha1": "07ff8e04f0e0ddf2bed7efb78f9c2ac997ead61d",
          "md5": "1cfa77eb65fa17b145500fca4330b193"
        }
      ]
    }
  ]
}
