{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "FirebaseRemoteConfig",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "FirebaseRemoteConfig-1.1.2.aar",
          "url": "FirebaseRemoteConfig-1.1.2.aar",
          "size": 27010,
          "sha512": "a93ac93c7aeb9c530aabc7684a5002494b47530bd5c85f089802f552fa8f409fb8f6152a4bb9e6c606d0c8a6a53790fe6b7f1dfe54fadf62aafdec9a8c87a3a7",
          "sha256": "d9ab15bdd226f7eb057b63c53f18877874181280fe505a840716013d848365ad",
          "sha1": "6cb698187c00c2e227fc1b37125c7744cf4ed4fe",
          "md5": "c214987f38f1a96c6f32026aa9e63023"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FirebaseAnalytics",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config-ktx",
          "version": {
            "requires": "19.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "FirebaseRemoteConfig-1.1.2.aar",
          "url": "FirebaseRemoteConfig-1.1.2.aar",
          "size": 27010,
          "sha512": "a93ac93c7aeb9c530aabc7684a5002494b47530bd5c85f089802f552fa8f409fb8f6152a4bb9e6c606d0c8a6a53790fe6b7f1dfe54fadf62aafdec9a8c87a3a7",
          "sha256": "d9ab15bdd226f7eb057b63c53f18877874181280fe505a840716013d848365ad",
          "sha1": "6cb698187c00c2e227fc1b37125c7744cf4ed4fe",
          "md5": "c214987f38f1a96c6f32026aa9e63023"
        }
      ]
    }
  ]
}
