{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "GoogleMapsLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GoogleMapsLib-1.1.2.aar",
          "url": "GoogleMapsLib-1.1.2.aar",
          "size": 67491,
          "sha512": "fbffa62f7d5f013f5d9c97e5899c8f1b3c63dcd86dbbd27d4a1bc9e3d887612ff25ef7f05983023320f1b29f07162d4841f607ab8be8d38a891371876b2cae9b",
          "sha256": "2222918ab301e42cc22329a7eaa0ec7d37733711cda65c88c2be29dc691d077e",
          "sha1": "c05e7eaf7680c9d849246f60080edaa0fb9d5e29",
          "md5": "a6fd152ebb2d6bc96922a9d8ac570e0d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "LocationLib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-places",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.libraries.places",
          "module": "places",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "GoogleMapsLib-1.1.2.aar",
          "url": "GoogleMapsLib-1.1.2.aar",
          "size": 67491,
          "sha512": "fbffa62f7d5f013f5d9c97e5899c8f1b3c63dcd86dbbd27d4a1bc9e3d887612ff25ef7f05983023320f1b29f07162d4841f607ab8be8d38a891371876b2cae9b",
          "sha256": "2222918ab301e42cc22329a7eaa0ec7d37733711cda65c88c2be29dc691d077e",
          "sha1": "c05e7eaf7680c9d849246f60080edaa0fb9d5e29",
          "md5": "a6fd152ebb2d6bc96922a9d8ac570e0d"
        }
      ]
    }
  ]
}
