{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "WeChatModule",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android-with-mta",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "WeChatModule-1.1.2.aar",
          "url": "WeChatModule-1.1.2.aar",
          "size": 41849,
          "sha512": "3c6891e0cbee2ee4caa6ec12721c9735c5639906e1209026b3be37d6e95483f499bfad3140bd5ab325fd20cd26ebb66a13a001b7fa16a3b24dd4e84a0dd21507",
          "sha256": "1cfab62dc3180e5aedc02ad59ba5b3c29d95c591e5e66c73d890487cecb71545",
          "sha1": "a57f5df4f8b770969b2cfc80612ffa1f55cf0ed8",
          "md5": "61ac7dca7dd807f8e0bbfe4f0ef19495"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android-with-mta",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "WeChatModule-1.1.2.aar",
          "url": "WeChatModule-1.1.2.aar",
          "size": 41849,
          "sha512": "3c6891e0cbee2ee4caa6ec12721c9735c5639906e1209026b3be37d6e95483f499bfad3140bd5ab325fd20cd26ebb66a13a001b7fa16a3b24dd4e84a0dd21507",
          "sha256": "1cfab62dc3180e5aedc02ad59ba5b3c29d95c591e5e66c73d890487cecb71545",
          "sha1": "a57f5df4f8b770969b2cfc80612ffa1f55cf0ed8",
          "md5": "61ac7dca7dd807f8e0bbfe4f0ef19495"
        }
      ]
    }
  ]
}
