{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "SuperAppsLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "SuperAppsLib-1.1.2.aar",
          "url": "SuperAppsLib-1.1.2.aar",
          "size": 74204,
          "sha512": "fcf7cbd6e6cafe476257c0ae356d0c771647e8bd8b159fd706c905a657b5c624c66c6d22793b9eb19d8191fc902920ab872bcd4314d8ff065c737f43205e1784",
          "sha256": "863588aeb9f7654ced3048bc0c74f20a28b5aeb6652363dba0d80221f091df7e",
          "sha1": "fba73dbe23b807f62991b5a60d0e4c89be6ed884",
          "md5": "714b6287858b9569d3749d4d8ac9b6fb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "SuperAppsLib-1.1.2.aar",
          "url": "SuperAppsLib-1.1.2.aar",
          "size": 74204,
          "sha512": "fcf7cbd6e6cafe476257c0ae356d0c771647e8bd8b159fd706c905a657b5c624c66c6d22793b9eb19d8191fc902920ab872bcd4314d8ff065c737f43205e1784",
          "sha256": "863588aeb9f7654ced3048bc0c74f20a28b5aeb6652363dba0d80221f091df7e",
          "sha1": "fba73dbe23b807f62991b5a60d0e4c89be6ed884",
          "md5": "714b6287858b9569d3749d4d8ac9b6fb"
        }
      ]
    }
  ]
}
