{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "MediaPlayer",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MediaPlayer-1.1.2.aar",
          "url": "MediaPlayer-1.1.2.aar",
          "size": 308358,
          "sha512": "dd8b11d6feeca9e0de2913842faa83178e1a5899c0a612bb1f2481a9640b339274054d65a842dddf774e7ebb1ae55aeb9705af298e373133c3c76d215429f9aa",
          "sha256": "7e31f45616b7761c6e1f4e3c1146360c9d2ab74ade512947f418b060f90d286d",
          "sha1": "e4d848846f917a57c0b26a52d11de8a8e7ce9cfb",
          "md5": "99272bb26ae229e34fef2876d63d0dee"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "MediaPlayer-1.1.2.aar",
          "url": "MediaPlayer-1.1.2.aar",
          "size": 308358,
          "sha512": "dd8b11d6feeca9e0de2913842faa83178e1a5899c0a612bb1f2481a9640b339274054d65a842dddf774e7ebb1ae55aeb9705af298e373133c3c76d215429f9aa",
          "sha256": "7e31f45616b7761c6e1f4e3c1146360c9d2ab74ade512947f418b060f90d286d",
          "sha1": "e4d848846f917a57c0b26a52d11de8a8e7ce9cfb",
          "md5": "99272bb26ae229e34fef2876d63d0dee"
        }
      ]
    }
  ]
}
