import { ModuleWithProviders, NgModule } from "@angular/core";
import { Routes, RouterModule } from "@angular/router";
$data.PanelsNotEntryPoint: { obj | import { $obj.FullName$Component \} from "app/$obj.ProjectPath$/$gx.ToLower.(obj.FileName)$.component" }; separator=";\r\n"$;

export const moduleRoutes: Routes = [
  $data.PanelsNotEntryPoint: { obj | { path: "$obj.RoutingPath$", component: $obj.FullName$Component \} }; separator = ",\r\n"$
];

@NgModule({
  imports: [RouterModule.forChild(moduleRoutes)],
  exports: [RouterModule]
})
export class SharedRoutingModule {}
