import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from "@angular/core";

import { FormsModule } from "@angular/forms";
import { CommonModule } from "@angular/common";
import { CommonModule as GxCommonModule } from "./common.module";

$data.UserControls: { obj | import { $obj.FullName$Component \} from "usercontrols/$obj.ProjectPath$/$gx.ToLower.(obj.FileName)$.component" }; separator=";\r\n"$;
$data.UserControlsGlobalImports: { obj | $obj.Source$ }; separator="\r\n"$

@NgModule({
  imports: [
    CommonModule, 
    FormsModule,
    GxCommonModule
    $data.UserControlsGlobalImports: { obj |,$obj.Modules$ }; separator="\r\n"$
  ],
  declarations: [
    $data.UserControls: { obj |$obj.FullName$Component }; separator = ",\r\n"$
  ],
  exports: [
    $data.UserControls: { obj |$obj.FullName$Component }; separator = ",\r\n"$
  ],
  bootstrap: [],
  providers: [],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class UsercontrolsModule {
}
