{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "FlexibleClient",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.genexus",
          "module": "gxandroid",
          "version": {
            "requires": "2.6.1"
          },
          "excludes": [
            {
              "group": "stax",
              "module": "stax-api"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-jdk15on"
            },
            {
              "group": "xpp3",
              "module": "*"
            },
            {
              "group": "org.apache.santuario",
              "module": "xmlsec"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "FlexibleClient-1.1.2.aar",
          "url": "FlexibleClient-1.1.2.aar",
          "size": 2452464,
          "sha512": "651ef1123dc964748a8cafc184f00609ea29eb9a39d3055a480aa4b0e9213c70835f3a2c2e3da5798a5e39a9bcf5716334b615ad06eb8497c9a04d67d7649a44",
          "sha256": "9ce4b96e0654437f9977296fe779aa4398b665734f915abb99eff40c477ac6f0",
          "sha1": "bd80e881972fcd0e56066ed79fa342f5a5b3c5cf",
          "md5": "6fb4179bd951ed893aa388296621ee11"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus",
          "module": "gxandroid",
          "version": {
            "requires": "2.6.1"
          },
          "excludes": [
            {
              "group": "stax",
              "module": "stax-api"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-jdk15on"
            },
            {
              "group": "xpp3",
              "module": "*"
            },
            {
              "group": "org.apache.santuario",
              "module": "xmlsec"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "org.simpleframework",
          "module": "simple-xml",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "stax",
              "module": "*"
            },
            {
              "group": "xpp3",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "roundedimageview",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "me.leolin",
          "module": "ShortcutBadger",
          "version": {
            "requires": "1.1.22"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "FlexibleClient-1.1.2.aar",
          "url": "FlexibleClient-1.1.2.aar",
          "size": 2452464,
          "sha512": "651ef1123dc964748a8cafc184f00609ea29eb9a39d3055a480aa4b0e9213c70835f3a2c2e3da5798a5e39a9bcf5716334b615ad06eb8497c9a04d67d7649a44",
          "sha256": "9ce4b96e0654437f9977296fe779aa4398b665734f915abb99eff40c477ac6f0",
          "sha1": "bd80e881972fcd0e56066ed79fa342f5a5b3c5cf",
          "md5": "6fb4179bd951ed893aa388296621ee11"
        }
      ]
    }
  ]
}
