{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "LiveEditingLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "LiveEditingLib-1.1.2.aar",
          "url": "LiveEditingLib-1.1.2.aar",
          "size": 118632,
          "sha512": "c42089f49ca59423fbdc34fc423bb820cf44003703e4eef2d74e0e647a95e28f9162c6127601f7dd1864ea3a76df35c544dd13b3c490181d98c6645f21d4a264",
          "sha256": "7739c0842b8794d501f9f981bf6236e7e72e14b9549f7f3e386a6b014ab87e48",
          "sha1": "778ced7d52e5f74700f9166c324369c703a99e6e",
          "md5": "3b36d3524a34310e0c6c98659f2b2873"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.37"
          }
        }
      ],
      "files": [
        {
          "name": "LiveEditingLib-1.1.2.aar",
          "url": "LiveEditingLib-1.1.2.aar",
          "size": 118632,
          "sha512": "c42089f49ca59423fbdc34fc423bb820cf44003703e4eef2d74e0e647a95e28f9162c6127601f7dd1864ea3a76df35c544dd13b3c490181d98c6645f21d4a264",
          "sha256": "7739c0842b8794d501f9f981bf6236e7e72e14b9549f7f3e386a6b014ab87e48",
          "sha1": "778ced7d52e5f74700f9166c324369c703a99e6e",
          "md5": "3b36d3524a34310e0c6c98659f2b2873"
        }
      ]
    }
  ]
}
