{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "FirebaseAnalytics",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "FirebaseAnalytics-1.1.2.aar",
          "url": "FirebaseAnalytics-1.1.2.aar",
          "size": 26858,
          "sha512": "6da14a443ef03432b5d28f54421a391e7fbc0ee372d89051c26cd857c8f071df5e4339eded5e2f26cb3d925ba45646f4a28b8aaa88c974dd22b14dcf87bd9b90",
          "sha256": "5888f628c34dfdb4020bdb1f68b555fdd70dfb6ad26e0b6e61ab78343b64b3e3",
          "sha1": "a5458ebe4cb86b8e8097e536b99d3cd44000a90d",
          "md5": "518d38a2b9a22b4b05958b2ab8e42a97"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "17.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "version": {
            "requires": "17.4.1"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "FirebaseAnalytics-1.1.2.aar",
          "url": "FirebaseAnalytics-1.1.2.aar",
          "size": 26858,
          "sha512": "6da14a443ef03432b5d28f54421a391e7fbc0ee372d89051c26cd857c8f071df5e4339eded5e2f26cb3d925ba45646f4a28b8aaa88c974dd22b14dcf87bd9b90",
          "sha256": "5888f628c34dfdb4020bdb1f68b555fdd70dfb6ad26e0b6e61ab78343b64b3e3",
          "sha1": "a5458ebe4cb86b8e8097e536b99d3cd44000a90d",
          "md5": "518d38a2b9a22b4b05958b2ab8e42a97"
        }
      ]
    }
  ]
}
