{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "LocationLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "LocationLib-1.1.2.aar",
          "url": "LocationLib-1.1.2.aar",
          "size": 244811,
          "sha512": "821ad5dcf311d7a86aae791ca5a53e595a28f385e64d37bab8d142f71e4088f7cdac5c574e85d00f05fb7d7f64cbf9997dce05dc2fa4e4b5c46c71ba7bc9e565",
          "sha256": "0fe8d303332f7a8601a9b50e4d31623ef0dfbdf291b37c973c3cf902cb0fc79d",
          "sha1": "35fef51ff73bec45e70fd95c27f8439e53fba507",
          "md5": "f2c96d2f6548a7fb99b63cceccd48f13"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "SimpleKMLLib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-base"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LocationLib-1.1.2.aar",
          "url": "LocationLib-1.1.2.aar",
          "size": 244811,
          "sha512": "821ad5dcf311d7a86aae791ca5a53e595a28f385e64d37bab8d142f71e4088f7cdac5c574e85d00f05fb7d7f64cbf9997dce05dc2fa4e4b5c46c71ba7bc9e565",
          "sha256": "0fe8d303332f7a8601a9b50e4d31623ef0dfbdf291b37c973c3cf902cb0fc79d",
          "sha1": "35fef51ff73bec45e70fd95c27f8439e53fba507",
          "md5": "f2c96d2f6548a7fb99b63cceccd48f13"
        }
      ]
    }
  ]
}
