{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "FilePicker",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "FilePicker-1.1.2.aar",
          "url": "FilePicker-1.1.2.aar",
          "size": 66691,
          "sha512": "ca5f3c07850c3ad8cf42ee85a7d095cfd610010ae0ab15ece1df61fe5398832943e29aeafdd4fd5808ff85cd70b1bce27d0b88feaf6ca6a29bc45e0fe44ee30c",
          "sha256": "9476b458f054669f8b252f81d72c55c392eba9fdb8a30acc53503cb1e10b1ba6",
          "sha1": "45f62876c621686e70ce03d46af99470c223a5ad",
          "md5": "5e5c9e44cbaebd33fdd499fe8f21e1d8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "FilePicker-1.1.2.aar",
          "url": "FilePicker-1.1.2.aar",
          "size": 66691,
          "sha512": "ca5f3c07850c3ad8cf42ee85a7d095cfd610010ae0ab15ece1df61fe5398832943e29aeafdd4fd5808ff85cd70b1bce27d0b88feaf6ca6a29bc45e0fe44ee30c",
          "sha256": "9476b458f054669f8b252f81d72c55c392eba9fdb8a30acc53503cb1e10b1ba6",
          "sha1": "45f62876c621686e70ce03d46af99470c223a5ad",
          "md5": "5e5c9e44cbaebd33fdd499fe8f21e1d8"
        }
      ]
    }
  ]
}
