{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "SqlDroidBase",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "SqlDroidBase-1.1.2.aar",
          "url": "SqlDroidBase-1.1.2.aar",
          "size": 44737,
          "sha512": "7bd6fe30861f44c96059ef024ba58cd7255a22e0ef949d9891010861c0e8f58134c9c6a7a27e58e8c0405bfc24eca1dd9b0c10b9165ee0459e256a0889199306",
          "sha256": "afbc0cee48ff5182d9bb9f75497f3e008278efc7ad227c8542b50e96f2addc69",
          "sha1": "c47e7176a4de423f8698bb769fe9a1b9780a182b",
          "md5": "5d272a438dbb794eada9ded2ed189874"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "SqlDroidBase-1.1.2.aar",
          "url": "SqlDroidBase-1.1.2.aar",
          "size": 44737,
          "sha512": "7bd6fe30861f44c96059ef024ba58cd7255a22e0ef949d9891010861c0e8f58134c9c6a7a27e58e8c0405bfc24eca1dd9b0c10b9165ee0459e256a0889199306",
          "sha256": "afbc0cee48ff5182d9bb9f75497f3e008278efc7ad227c8542b50e96f2addc69",
          "sha1": "c47e7176a4de423f8698bb769fe9a1b9780a182b",
          "md5": "5d272a438dbb794eada9ded2ed189874"
        }
      ]
    }
  ]
}
