{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "Facebook",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Facebook-1.1.2.aar",
          "url": "Facebook-1.1.2.aar",
          "size": 45789,
          "sha512": "3bdbb7d5c9a2d86a8262d1208633a1264773642557fa927e4e0386f3fa898f24f35ad25d4bbcd9959c0553cc0f6c05eb40e13c3474db3d6c3f00ad4e4d11673f",
          "sha256": "3e1ca64f322457aa16001c8249c71a8114f2fc3e7ef099e4b786ea0bf09de32a",
          "sha1": "dd5e6d2e363d3c2b880ef7763733562fc35ca358",
          "md5": "22ef308f1e106a57d4aaa38ec4684bfc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "11.3.0"
          },
          "excludes": [
            {
              "group": "androidx.cardview",
              "module": "cardview"
            }
          ]
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "Facebook-1.1.2.aar",
          "url": "Facebook-1.1.2.aar",
          "size": 45789,
          "sha512": "3bdbb7d5c9a2d86a8262d1208633a1264773642557fa927e4e0386f3fa898f24f35ad25d4bbcd9959c0553cc0f6c05eb40e13c3474db3d6c3f00ad4e4d11673f",
          "sha256": "3e1ca64f322457aa16001c8249c71a8114f2fc3e7ef099e4b786ea0bf09de32a",
          "sha1": "dd5e6d2e363d3c2b880ef7763733562fc35ca358",
          "md5": "22ef308f1e106a57d4aaa38ec4684bfc"
        }
      ]
    }
  ]
}
