{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "ChartsLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ChartsLib-1.1.2.aar",
          "url": "ChartsLib-1.1.2.aar",
          "size": 43173,
          "sha512": "a0182ba73609e9f403541106f489ca7f65c0ccd5f5beeb4fbcaf6fb818694e8c2f51769d19653a8defd7b6a6c62d27e0edbf7fb1c5b9b3735560ddeed739f0bb",
          "sha256": "d2b4ef772c481daecd4c7e4026019a1824fdd416027dded3504aa50c98a68d8b",
          "sha1": "6c39d1a816037a37d00613e2b8c6b07bebf7c265",
          "md5": "4f85dd4eaa0bedb5eb5d62f7f5412eb5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.github.PhilJay",
          "module": "MPAndroidChart",
          "version": {
            "requires": "v3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ChartsLib-1.1.2.aar",
          "url": "ChartsLib-1.1.2.aar",
          "size": 43173,
          "sha512": "a0182ba73609e9f403541106f489ca7f65c0ccd5f5beeb4fbcaf6fb818694e8c2f51769d19653a8defd7b6a6c62d27e0edbf7fb1c5b9b3735560ddeed739f0bb",
          "sha256": "d2b4ef772c481daecd4c7e4026019a1824fdd416027dded3504aa50c98a68d8b",
          "sha1": "6c39d1a816037a37d00613e2b8c6b07bebf7c265",
          "md5": "4f85dd4eaa0bedb5eb5d62f7f5412eb5"
        }
      ]
    }
  ]
}
