{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "SimpleKMLLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "SimpleKMLLib-1.1.2.aar",
          "url": "SimpleKMLLib-1.1.2.aar",
          "size": 75028,
          "sha512": "796a09d87b68642b291d68eb8d926fa133b25fa9ac0bd497ec80daa35e868f878fd73b33d6176942ce1a8b33949ee77a1b1368947f443db5e9928537fed0d919",
          "sha256": "f04dbd2bf33ea6eb1034f2e78fbd49be4ea7fb3f08d7dba30406d82b29d0a94e",
          "sha1": "fb3bd331a7537c183e82c7ba7a56cc9d6444e950",
          "md5": "b4a697601e759c68e672c86bdb1502d3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.simpleframework",
          "module": "simple-xml",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "stax",
              "module": "*"
            },
            {
              "group": "xpp3",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "SimpleKMLLib-1.1.2.aar",
          "url": "SimpleKMLLib-1.1.2.aar",
          "size": 75028,
          "sha512": "796a09d87b68642b291d68eb8d926fa133b25fa9ac0bd497ec80daa35e868f878fd73b33d6176942ce1a8b33949ee77a1b1368947f443db5e9928537fed0d919",
          "sha256": "f04dbd2bf33ea6eb1034f2e78fbd49be4ea7fb3f08d7dba30406d82b29d0a94e",
          "sha1": "fb3bd331a7537c183e82c7ba7a56cc9d6444e950",
          "md5": "b4a697601e759c68e672c86bdb1502d3"
        }
      ]
    }
  ]
}
