{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "VideoOperationsLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "VideoOperationsLib-1.1.2.aar",
          "url": "VideoOperationsLib-1.1.2.aar",
          "size": 36199,
          "sha512": "3c3e12f29dee000a6325dd7ea2e4b3f92dc5f00640a40769d56087357abc5fe08e33a8de5868628114e4c3b2eb64253d6c1ed06f9a00f020a9f2800607048c13",
          "sha256": "bbd35b70f2cfef59fa74b203e64a2f2d4c877c5d4be9d200d7d3fb399192999d",
          "sha1": "53247bbd21848ecb87ebf6a0fb663a61ecce7ae2",
          "md5": "4258df780bd8700d5e25d59901dd6c91"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.arthenica",
          "module": "mobile-ffmpeg-full-gpl",
          "version": {
            "requires": "4.3.1.LTS"
          }
        }
      ],
      "files": [
        {
          "name": "VideoOperationsLib-1.1.2.aar",
          "url": "VideoOperationsLib-1.1.2.aar",
          "size": 36199,
          "sha512": "3c3e12f29dee000a6325dd7ea2e4b3f92dc5f00640a40769d56087357abc5fe08e33a8de5868628114e4c3b2eb64253d6c1ed06f9a00f020a9f2800607048c13",
          "sha256": "bbd35b70f2cfef59fa74b203e64a2f2d4c877c5d4be9d200d7d3fb399192999d",
          "sha1": "53247bbd21848ecb87ebf6a0fb663a61ecce7ae2",
          "md5": "4258df780bd8700d5e25d59901dd6c91"
        }
      ]
    }
  ]
}
