{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "HMSOneSignalModule",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "HMSOneSignalModule-1.1.2.aar",
          "url": "HMSOneSignalModule-1.1.2.aar",
          "size": 25415,
          "sha512": "f0d3cdab23c3162bc5a14ea8ca5a36334801d0161474128325bedcb0805905e37ea9f7fb59b0ffbac525065fdaacc2d6935d929642148f38a9c8af4bba947aa7",
          "sha256": "c18a462cbf23b5f0043c193c0f43c0865e3572d21ce737eb53d6479302264107",
          "sha1": "679a38e03bb8c026e4374f53c756f4af23151edf",
          "md5": "818844f0817a9ae3fb6538c769b35457"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.onesignal",
          "module": "OneSignal",
          "version": {
            "requires": "4.6.3"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "OneSignalModule",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "HMSCommon",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.huawei.hms",
          "module": "push",
          "version": {
            "requires": "6.3.0.302"
          }
        }
      ],
      "files": [
        {
          "name": "HMSOneSignalModule-1.1.2.aar",
          "url": "HMSOneSignalModule-1.1.2.aar",
          "size": 25415,
          "sha512": "f0d3cdab23c3162bc5a14ea8ca5a36334801d0161474128325bedcb0805905e37ea9f7fb59b0ffbac525065fdaacc2d6935d929642148f38a9c8af4bba947aa7",
          "sha256": "c18a462cbf23b5f0043c193c0f43c0865e3572d21ce737eb53d6479302264107",
          "sha1": "679a38e03bb8c026e4374f53c756f4af23151edf",
          "md5": "818844f0817a9ae3fb6538c769b35457"
        }
      ]
    }
  ]
}
