{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "MapboxLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MapboxLib-1.1.2.aar",
          "url": "MapboxLib-1.1.2.aar",
          "size": 106960,
          "sha512": "4fc3ed4c2c4c7a6de3e4af1486e89bf6b7be922959049c69e81275600ac7ee34a83ea9d8ef78902f0a0ef5046f103a42a4ea71944e0f611b0d285a58c6df4161",
          "sha256": "749b8bab098143e0d6c9b1ea4ce6eb055bb2d43e332af2d4da231f91540f9b3d",
          "sha1": "a466003d814bfcb8625cbf33d294ebb0d14c34ba",
          "md5": "015c956f692d9fe65d0ab0a6b74245c8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "LocationLib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-android-sdk",
          "version": {
            "requires": "9.5.0"
          }
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-android-plugin-annotation-v9",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-android-plugin-traffic-v9",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-android-plugin-offline-v9",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-sdk-services",
          "version": {
            "requires": "5.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "MapboxLib-1.1.2.aar",
          "url": "MapboxLib-1.1.2.aar",
          "size": 106960,
          "sha512": "4fc3ed4c2c4c7a6de3e4af1486e89bf6b7be922959049c69e81275600ac7ee34a83ea9d8ef78902f0a0ef5046f103a42a4ea71944e0f611b0d285a58c6df4161",
          "sha256": "749b8bab098143e0d6c9b1ea4ce6eb055bb2d43e332af2d4da231f91540f9b3d",
          "sha1": "a466003d814bfcb8625cbf33d294ebb0d14c34ba",
          "md5": "015c956f692d9fe65d0ab0a6b74245c8"
        }
      ]
    }
  ]
}
