{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "CoreUserControls",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CoreUserControls-1.1.2.aar",
          "url": "CoreUserControls-1.1.2.aar",
          "size": 197295,
          "sha512": "f73be35e44e8c7eecbbfcde1db5b7e76fee99791ce64694e4ae48116ded2648c24975eca300f14ac77e1880dbacb63a20b9cebfe83325b1b4c7bc8a9fdd0e4da",
          "sha256": "44d6c54526db28733ebdf10002c60eaa85e2d344de0e93193d87a39a0817bdc0",
          "sha1": "c9581cd7a05d833c7b7fa4c1ad682bbae39aff0a",
          "md5": "7d0d2f4d6067758895601e8b3f152e51"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "com.zolad",
          "module": "zoominimageview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "CoreUserControls-1.1.2.aar",
          "url": "CoreUserControls-1.1.2.aar",
          "size": 197295,
          "sha512": "f73be35e44e8c7eecbbfcde1db5b7e76fee99791ce64694e4ae48116ded2648c24975eca300f14ac77e1880dbacb63a20b9cebfe83325b1b4c7bc8a9fdd0e4da",
          "sha256": "44d6c54526db28733ebdf10002c60eaa85e2d344de0e93193d87a39a0817bdc0",
          "sha1": "c9581cd7a05d833c7b7fa4c1ad682bbae39aff0a",
          "md5": "7d0d2f4d6067758895601e8b3f152e51"
        }
      ]
    }
  ]
}
