{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "AnimationLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AnimationLib-1.1.2.aar",
          "url": "AnimationLib-1.1.2.aar",
          "size": 39308,
          "sha512": "a1e813347e857e08684f837495602dec6a20cbbf989d9eb91a5753d2f3b37982a1cba8fc617c3ad5822b856e753f2a00ff1dfe81a1369d69b983f183c3d6b387",
          "sha256": "8a130535229531988f5887ef80a50e5cd8a71ddc5c148225939e4d77eb597066",
          "sha1": "2155800ee168143ccc564b0505b9068a6a96a7a5",
          "md5": "f2bfee0a2afd03f6b0966ceb08f6d8a1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "AnimationLib-1.1.2.aar",
          "url": "AnimationLib-1.1.2.aar",
          "size": 39308,
          "sha512": "a1e813347e857e08684f837495602dec6a20cbbf989d9eb91a5753d2f3b37982a1cba8fc617c3ad5822b856e753f2a00ff1dfe81a1369d69b983f183c3d6b387",
          "sha256": "8a130535229531988f5887ef80a50e5cd8a71ddc5c148225939e4d77eb597066",
          "sha1": "2155800ee168143ccc564b0505b9068a6a96a7a5",
          "md5": "f2bfee0a2afd03f6b0966ceb08f6d8a1"
        }
      ]
    }
  ]
}
