{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "HMSMapKitLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "HMSMapKitLib-1.1.2.aar",
          "url": "HMSMapKitLib-1.1.2.aar",
          "size": 75916,
          "sha512": "53281e8756ba4ac433f2cc8426001e8bdd29698d55cfcb45a34f22cd8cca37c6336bb6823907d6fced91460c645eb545dd26ca58fd7670df8d29edc7626110cf",
          "sha256": "5ab8f88435feb847d18dff5f14b84683b6234c4f6060e16401efb4daa30a6af2",
          "sha1": "7c8e839289f2ec7692b7fd222ea4f270c6e3de26",
          "md5": "f48aca0c68db14a3afc17455e836eaae"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "LocationLib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "HMSCommon",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.huawei.hms",
          "module": "maps",
          "version": {
            "requires": "6.3.1.300"
          }
        }
      ],
      "files": [
        {
          "name": "HMSMapKitLib-1.1.2.aar",
          "url": "HMSMapKitLib-1.1.2.aar",
          "size": 75916,
          "sha512": "53281e8756ba4ac433f2cc8426001e8bdd29698d55cfcb45a34f22cd8cca37c6336bb6823907d6fced91460c645eb545dd26ca58fd7670df8d29edc7626110cf",
          "sha256": "5ab8f88435feb847d18dff5f14b84683b6234c4f6060e16401efb4daa30a6af2",
          "sha1": "7c8e839289f2ec7692b7fd222ea4f270c6e3de26",
          "md5": "f48aca0c68db14a3afc17455e836eaae"
        }
      ]
    }
  ]
}
