{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "AltBeacon",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AltBeacon-1.1.2.aar",
          "url": "AltBeacon-1.1.2.aar",
          "size": 70000,
          "sha512": "4d9684a5d2acbd2a8bde6384d3d44bbcb4146a7dcb33856e71282e6b17490d1278ceb93ae0ec83901c228881786c26098d58efb407e59b1794e831bc0779cf63",
          "sha256": "df1863e9f2e4c2a67f2fdf27b5ee40b48b68499bb53f52888fff47a30fb2b147",
          "sha1": "749c93f749e333242e15bbca5996bb0078a98999",
          "md5": "d709f69b5eec850e57290b298c39d99c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "AltBeacon-1.1.2.aar",
          "url": "AltBeacon-1.1.2.aar",
          "size": 70000,
          "sha512": "4d9684a5d2acbd2a8bde6384d3d44bbcb4146a7dcb33856e71282e6b17490d1278ceb93ae0ec83901c228881786c26098d58efb407e59b1794e831bc0779cf63",
          "sha256": "df1863e9f2e4c2a67f2fdf27b5ee40b48b68499bb53f52888fff47a30fb2b147",
          "sha1": "749c93f749e333242e15bbca5996bb0078a98999",
          "md5": "d709f69b5eec850e57290b298c39d99c"
        }
      ]
    }
  ]
}
