{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "CoreExternalObjects",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CoreExternalObjects-1.1.2.aar",
          "url": "CoreExternalObjects-1.1.2.aar",
          "size": 206215,
          "sha512": "bc539f2c0d7e063b9c00e9a96edfc13796d0b33016de4e30616791c433ff1229cf22b17a8ae245411510a2253e45014e012bf797b8eb280a11eb56fb7f994363",
          "sha256": "43a3fbab5a1d33be180000d88af580d5ca6fd1a20159d9f830a75509bdf0b69a",
          "sha1": "7a88f17911ddaa9f94355621fa70acbfba55777a",
          "md5": "659b253c90b9b1f446faad374ab8a252"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "CoreExternalObjects-1.1.2.aar",
          "url": "CoreExternalObjects-1.1.2.aar",
          "size": 206215,
          "sha512": "bc539f2c0d7e063b9c00e9a96edfc13796d0b33016de4e30616791c433ff1229cf22b17a8ae245411510a2253e45014e012bf797b8eb280a11eb56fb7f994363",
          "sha256": "43a3fbab5a1d33be180000d88af580d5ca6fd1a20159d9f830a75509bdf0b69a",
          "sha1": "7a88f17911ddaa9f94355621fa70acbfba55777a",
          "md5": "659b253c90b9b1f446faad374ab8a252"
        }
      ]
    }
  ]
}
