{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "HMSCommon",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "HMSCommon-1.1.2.aar",
          "url": "HMSCommon-1.1.2.aar",
          "size": 23969,
          "sha512": "0337df70c06085fb6da63e8708ba6ed55b43d8a9a88fc0528c0888c4009e974e3d76d28e7d274b44ea72835172f0025c5da30cf4df403294214e68e1526e1920",
          "sha256": "f0a259f49384eb7c3b2075ef2d4af27bde55d428c1152a11487ce028e7780c0c",
          "sha1": "34c1ed948217a898ad4054bc6169676f0939557d",
          "md5": "12c64acd7d066b5b7051450bfa8aa15e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.huawei.hms",
          "module": "hwid",
          "version": {
            "requires": "6.3.0.301"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "HMSCommon-1.1.2.aar",
          "url": "HMSCommon-1.1.2.aar",
          "size": 23969,
          "sha512": "0337df70c06085fb6da63e8708ba6ed55b43d8a9a88fc0528c0888c4009e974e3d76d28e7d274b44ea72835172f0025c5da30cf4df403294214e68e1526e1920",
          "sha256": "f0a259f49384eb7c3b2075ef2d4af27bde55d428c1152a11487ce028e7780c0c",
          "sha1": "34c1ed948217a898ad4054bc6169676f0939557d",
          "md5": "12c64acd7d066b5b7051450bfa8aa15e"
        }
      ]
    }
  ]
}
