{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "DeviceAuthentication",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "DeviceAuthentication-1.1.2.aar",
          "url": "DeviceAuthentication-1.1.2.aar",
          "size": 96734,
          "sha512": "7ce1f93d9ec545728cc0264f764d453a340e102fcddfcd9669d10ee6247ad156a7f3583b71b98961c6faccaaad86e411ce6a1e01dae409a8bf1fff8a92dfdb57",
          "sha256": "56b0b49433e35c637f73a5c37c3dc2a68319746aa2fb2c7d55cd47f341e899c2",
          "sha1": "eb208c3614e64f7e4d963cc93d9af87cdecab8fa",
          "md5": "ca978b9483ae1ecd097901230f40f651"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "DeviceAuthentication-1.1.2.aar",
          "url": "DeviceAuthentication-1.1.2.aar",
          "size": 96734,
          "sha512": "7ce1f93d9ec545728cc0264f764d453a340e102fcddfcd9669d10ee6247ad156a7f3583b71b98961c6faccaaad86e411ce6a1e01dae409a8bf1fff8a92dfdb57",
          "sha256": "56b0b49433e35c637f73a5c37c3dc2a68319746aa2fb2c7d55cd47f341e899c2",
          "sha1": "eb208c3614e64f7e4d963cc93d9af87cdecab8fa",
          "md5": "ca978b9483ae1ecd097901230f40f651"
        }
      ]
    }
  ]
}
