{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "WheelsLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "WheelsLib-1.1.2.aar",
          "url": "WheelsLib-1.1.2.aar",
          "size": 71614,
          "sha512": "e4a2a2ba07c08e913ae2dc083b44150b5dde5218525d48e80b39320846b0179c3cc38b54e5bfdbd8f729a370f634e3afceb0d566100bf058f45ac17faa4b095c",
          "sha256": "abeed7958ee6c87fee55e911c11bcd61595f077b9313e556b329076e3a16bddc",
          "sha1": "b038e2091f380192c4c80581bc4f185fd0a10047",
          "md5": "1f43fe64e5cab2029e89f7835659c510"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "spinner-library",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "WheelsLib-1.1.2.aar",
          "url": "WheelsLib-1.1.2.aar",
          "size": 71614,
          "sha512": "e4a2a2ba07c08e913ae2dc083b44150b5dde5218525d48e80b39320846b0179c3cc38b54e5bfdbd8f729a370f634e3afceb0d566100bf058f45ac17faa4b095c",
          "sha256": "abeed7958ee6c87fee55e911c11bcd61595f077b9313e556b329076e3a16bddc",
          "sha1": "b038e2091f380192c4c80581bc4f185fd0a10047",
          "md5": "1f43fe64e5cab2029e89f7835659c510"
        }
      ]
    }
  ]
}
