{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "HMSInAppBillingLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "HMSInAppBillingLib-1.1.2.aar",
          "url": "HMSInAppBillingLib-1.1.2.aar",
          "size": 54396,
          "sha512": "93b1ec90b8d8963e677a63fd8f0faf6034d735b07e4ecbc7c94b889c93558df324185d7cc1a7cae3db0d1047103934af0084d4080b24f2a0585ea785c08e3e0b",
          "sha256": "c074278112a64884ad2d3cd63b9d4666d92c647a80b4333b97d65d9592c64904",
          "sha1": "615a964236e15ae460c9d89226d6687fd29dfe13",
          "md5": "5a324a9ba98b9b3b5cf88696b61e243b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "HMSCommon",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.huawei.hms",
          "module": "iap",
          "version": {
            "requires": "6.3.0.300"
          }
        }
      ],
      "files": [
        {
          "name": "HMSInAppBillingLib-1.1.2.aar",
          "url": "HMSInAppBillingLib-1.1.2.aar",
          "size": 54396,
          "sha512": "93b1ec90b8d8963e677a63fd8f0faf6034d735b07e4ecbc7c94b889c93558df324185d7cc1a7cae3db0d1047103934af0084d4080b24f2a0585ea785c08e3e0b",
          "sha256": "c074278112a64884ad2d3cd63b9d4666d92c647a80b4333b97d65d9592c64904",
          "sha1": "615a964236e15ae460c9d89226d6687fd29dfe13",
          "md5": "5a324a9ba98b9b3b5cf88696b61e243b"
        }
      ]
    }
  ]
}
