{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "PrintLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PrintLib-1.1.2.aar",
          "url": "PrintLib-1.1.2.aar",
          "size": 36281,
          "sha512": "410c3163c3e6e151de6dda4d778afb40e3fddda33f6d191f346e8b060d9e52a75f13e897aad363489885faca551c4308267712dc6258efdd31d883f196f201e9",
          "sha256": "6b898840019c976cfa301ee6a03173cc2a38b8c72bf4ddbc3dc6f89558a8f683",
          "sha1": "a15bbeda9f643454401f00e4268e6042d48a6788",
          "md5": "30837d6f99e58980c508df6bce01b18f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "PrintLib-1.1.2.aar",
          "url": "PrintLib-1.1.2.aar",
          "size": 36281,
          "sha512": "410c3163c3e6e151de6dda4d778afb40e3fddda33f6d191f346e8b060d9e52a75f13e897aad363489885faca551c4308267712dc6258efdd31d883f196f201e9",
          "sha256": "6b898840019c976cfa301ee6a03173cc2a38b8c72bf4ddbc3dc6f89558a8f683",
          "sha1": "a15bbeda9f643454401f00e4268e6042d48a6788",
          "md5": "30837d6f99e58980c508df6bce01b18f"
        }
      ]
    }
  ]
}
