{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "MercadoPagoLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MercadoPagoLib-1.1.2.aar",
          "url": "MercadoPagoLib-1.1.2.aar",
          "size": 33772,
          "sha512": "9565a2d2f6a41114d414afd5a4ffc342804cf26777601195bf130d1bcc6784995780726416a20ce2d1ffb725681ea840a9c207383fbbd380e32512f4e708e121",
          "sha256": "528040cc3df4cc1d9645f70145dac70aed5d2d959078cd2c62e85b806324ed2d",
          "sha1": "1faa1f9a3c75a8a8fc16c42ba403b4836ac5b9fe",
          "md5": "715ef7b51d02efa2fa6d982809ae0bac"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.mercadopago.android.px",
          "module": "services",
          "version": {
            "requires": "4.28.0"
          }
        }
      ],
      "files": [
        {
          "name": "MercadoPagoLib-1.1.2.aar",
          "url": "MercadoPagoLib-1.1.2.aar",
          "size": 33772,
          "sha512": "9565a2d2f6a41114d414afd5a4ffc342804cf26777601195bf130d1bcc6784995780726416a20ce2d1ffb725681ea840a9c207383fbbd380e32512f4e708e121",
          "sha256": "528040cc3df4cc1d9645f70145dac70aed5d2d959078cd2c62e85b806324ed2d",
          "sha1": "1faa1f9a3c75a8a8fc16c42ba403b4836ac5b9fe",
          "md5": "715ef7b51d02efa2fa6d982809ae0bac"
        }
      ]
    }
  ]
}
