{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "CardScannerLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CardScannerLib-1.1.2.aar",
          "url": "CardScannerLib-1.1.2.aar",
          "size": 32170,
          "sha512": "0118e9bdf0332408eace7b1cc8a6e91f436501cfd3f99cbcdf855f179e978217c139ef6e06b8fc6ce8dfccab8d814d22fdcaa0b022ee9da5d7a4be2e9e6ef581",
          "sha256": "cda63aa1731b967a17c8c2f894282313b16338a9e8e7bc7dc30ba23ba7ba7019",
          "sha1": "62cf0c0ec2c7e34bae3fc74125ae39c631bbdd22",
          "md5": "66c131763a8ebe70a4710a3d9dcf682f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.card",
          "module": "android-sdk",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "CardScannerLib-1.1.2.aar",
          "url": "CardScannerLib-1.1.2.aar",
          "size": 32170,
          "sha512": "0118e9bdf0332408eace7b1cc8a6e91f436501cfd3f99cbcdf855f179e978217c139ef6e06b8fc6ce8dfccab8d814d22fdcaa0b022ee9da5d7a4be2e9e6ef581",
          "sha256": "cda63aa1731b967a17c8c2f894282313b16338a9e8e7bc7dc30ba23ba7ba7019",
          "sha1": "62cf0c0ec2c7e34bae3fc74125ae39c631bbdd22",
          "md5": "66c131763a8ebe70a4710a3d9dcf682f"
        }
      ]
    }
  ]
}
