{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "MLKitLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MLKitLib-1.1.2.aar",
          "url": "MLKitLib-1.1.2.aar",
          "size": 40861,
          "sha512": "e1f95fdb473dfd73ccfb01b7859fa087c3152a1332237fd2cb954c2a4d4e9ee7e443e55307664cd589e536e6d312ce08568c93de81c7ea2db2dce30ad7287914",
          "sha256": "854373c296162acc852c293c15b948f967e1e7a1849bc722c29cbad17406e75d",
          "sha1": "d513dd77e6523292e044546bce7858ce84fd57f4",
          "md5": "6e8f41f804c71a492dd9082031734f92"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "24.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-image-label-model",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-face-model",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-object-detection-model",
          "version": {
            "requires": "19.0.3"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-natural-language",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-natural-language-language-id-model",
          "version": {
            "requires": "20.0.7"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-natural-language-translate-model",
          "version": {
            "requires": "20.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "MLKitLib-1.1.2.aar",
          "url": "MLKitLib-1.1.2.aar",
          "size": 40861,
          "sha512": "e1f95fdb473dfd73ccfb01b7859fa087c3152a1332237fd2cb954c2a4d4e9ee7e443e55307664cd589e536e6d312ce08568c93de81c7ea2db2dce30ad7287914",
          "sha256": "854373c296162acc852c293c15b948f967e1e7a1849bc722c29cbad17406e75d",
          "sha1": "d513dd77e6523292e044546bce7858ce84fd57f4",
          "md5": "6e8f41f804c71a492dd9082031734f92"
        }
      ]
    }
  ]
}
