{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "GoogleMobileAds",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GoogleMobileAds-1.1.2.aar",
          "url": "GoogleMobileAds-1.1.2.aar",
          "size": 33162,
          "sha512": "35b5a56ca6c24db21169b74ceee651194f9b2f5fbbe5106a5edeab603e3c19522326f8db1fa6c3b0f12702f174b734926c9ada8799ca6613cfbccb25b2b6868b",
          "sha256": "520860658d6546528ef1034ebdf59f5f10cc84ae0ba1d624de4f73da59399da1",
          "sha1": "50cc07660eaf2b288a9425a988136adf0cda4be9",
          "md5": "d334f5c1bfd6eded4faffe845d173883"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "AdsLib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "19.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "GoogleMobileAds-1.1.2.aar",
          "url": "GoogleMobileAds-1.1.2.aar",
          "size": 33162,
          "sha512": "35b5a56ca6c24db21169b74ceee651194f9b2f5fbbe5106a5edeab603e3c19522326f8db1fa6c3b0f12702f174b734926c9ada8799ca6613cfbccb25b2b6868b",
          "sha256": "520860658d6546528ef1034ebdf59f5f10cc84ae0ba1d624de4f73da59399da1",
          "sha1": "50cc07660eaf2b288a9425a988136adf0cda4be9",
          "md5": "d334f5c1bfd6eded4faffe845d173883"
        }
      ]
    }
  ]
}
