{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "AdsLib",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AdsLib-1.1.2.aar",
          "url": "AdsLib-1.1.2.aar",
          "size": 29858,
          "sha512": "30e147801790d0e33ed2b781c6dc98cbe544480021f8376cd81d155ace21207ee121123ef69eb8eb58b275008cc05537189553fc290a19d76b6d6a4e2291a75c",
          "sha256": "020c681f066d629629864eb5f5519e4401679f7f6358e288bf0c268683fba9e2",
          "sha1": "763a84e3c5214fe36d8c95492f0c4ab939180358",
          "md5": "2ef86ae858eed69511219eca1bd1655c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "AdsLib-1.1.2.aar",
          "url": "AdsLib-1.1.2.aar",
          "size": 29858,
          "sha512": "30e147801790d0e33ed2b781c6dc98cbe544480021f8376cd81d155ace21207ee121123ef69eb8eb58b275008cc05537189553fc290a19d76b6d6a4e2291a75c",
          "sha256": "020c681f066d629629864eb5f5519e4401679f7f6358e288bf0c268683fba9e2",
          "sha1": "763a84e3c5214fe36d8c95492f0c4ab939180358",
          "md5": "2ef86ae858eed69511219eca1bd1655c"
        }
      ]
    }
  ]
}
