{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "AugmentedReality",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "AugmentedReality-1.1.2.aar",
          "url": "AugmentedReality-1.1.2.aar",
          "size": 76483,
          "sha512": "b7a67a6178791e94b01029c32f00d260be7dae78c4fb05c9ff410f83797540ea3342bcd5feb3c3f318d337744411c6b54da31f4ae135bca08339ebc92f472b44",
          "sha256": "a314222a8093a46b13b184cde895e0ea5410e179a157f84b1e387db2186d8276",
          "sha1": "3a9a794e1363ea75128f606b7956453be609c3b8",
          "md5": "ead6f4bea5e5a3c6701305212124e3b5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "com.google.ar.sceneform.ux",
          "module": "sceneform-ux",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "com.google.ar.sceneform",
          "module": "assets",
          "version": {
            "requires": "1.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "AugmentedReality-1.1.2.aar",
          "url": "AugmentedReality-1.1.2.aar",
          "size": 76483,
          "sha512": "b7a67a6178791e94b01029c32f00d260be7dae78c4fb05c9ff410f83797540ea3342bcd5feb3c3f318d337744411c6b54da31f4ae135bca08339ebc92f472b44",
          "sha256": "a314222a8093a46b13b184cde895e0ea5410e179a157f84b1e387db2186d8276",
          "sha1": "3a9a794e1363ea75128f606b7956453be609c3b8",
          "md5": "ead6f4bea5e5a3c6701305212124e3b5"
        }
      ]
    }
  ]
}
