{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "HMSAnalytics",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "HMSAnalytics-1.1.2.aar",
          "url": "HMSAnalytics-1.1.2.aar",
          "size": 27510,
          "sha512": "a2a5d0f6ee639772d240238cb23705a3ab075c4c30e3f0a3aacb9506155a9657be094033ab9f370773cdc30d75e7de377750b4d6fb7aca9ab9c8faaa393554fe",
          "sha256": "edd57282b263b51757e3ce1b0ec039916cfdd6ec8d7e2115f0a5caa8ae92f164",
          "sha1": "e0c0ceb29d062c9f6ae06e00a55b61090dd07f79",
          "md5": "6187ed9b67b620d9a6cd89b49a2fead8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.huawei.hms",
          "module": "hianalytics",
          "version": {
            "requires": "6.4.0.300"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "HMSCommon",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "HMSAnalytics-1.1.2.aar",
          "url": "HMSAnalytics-1.1.2.aar",
          "size": 27510,
          "sha512": "a2a5d0f6ee639772d240238cb23705a3ab075c4c30e3f0a3aacb9506155a9657be094033ab9f370773cdc30d75e7de377750b4d6fb7aca9ab9c8faaa393554fe",
          "sha256": "edd57282b263b51757e3ce1b0ec039916cfdd6ec8d7e2115f0a5caa8ae92f164",
          "sha1": "e0c0ceb29d062c9f6ae06e00a55b61090dd07f79",
          "md5": "6187ed9b67b620d9a6cd89b49a2fead8"
        }
      ]
    }
  ]
}
