{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "GoogleAnalytics",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GoogleAnalytics-1.1.2.aar",
          "url": "GoogleAnalytics-1.1.2.aar",
          "size": 26743,
          "sha512": "901323cc6bdb1798761e147e8e2ef92b60368d8c20dad770dbfe11968fd90ee929b0d930e724322f7b95d30020d22538b50b46ad2c9ba9fbc31dcd84fe5da7de",
          "sha256": "e77cec3bb2e641b5c98224c70768fe0e2a0e70f88c259c50bb6d2a018125c766",
          "sha1": "60ebc182b0a1c2783a0a11c5318adb800a8998f2",
          "md5": "f78c69b152e0337c8c0aae8777d4fb35"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-analytics",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "GoogleAnalytics-1.1.2.aar",
          "url": "GoogleAnalytics-1.1.2.aar",
          "size": 26743,
          "sha512": "901323cc6bdb1798761e147e8e2ef92b60368d8c20dad770dbfe11968fd90ee929b0d930e724322f7b95d30020d22538b50b46ad2c9ba9fbc31dcd84fe5da7de",
          "sha256": "e77cec3bb2e641b5c98224c70768fe0e2a0e70f88c259c50bb6d2a018125c766",
          "sha1": "60ebc182b0a1c2783a0a11c5318adb800a8998f2",
          "md5": "f78c69b152e0337c8c0aae8777d4fb35"
        }
      ]
    }
  ]
}
