{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "AlipayModule",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AlipayModule-1.1.2.aar",
          "url": "AlipayModule-1.1.2.aar",
          "size": 333146,
          "sha512": "b815dc7e07c872763dbec756f381327feca4cf8aef31fa0ed0cc5bb60091eb0fdef3edda0c1b1f7ccd9e3479dcb651710c5f893d2e61853ce7242de9e0c953a0",
          "sha256": "8af65907f975892e09a2ab4178518638e6e52cc453d16643947dc2480fb88cd5",
          "sha1": "a653e816179e2eeac21949ca29e306ff508478d6",
          "md5": "002a5062ccd05db580670eb8887df879"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "AlipayModule-1.1.2.aar",
          "url": "AlipayModule-1.1.2.aar",
          "size": 333146,
          "sha512": "b815dc7e07c872763dbec756f381327feca4cf8aef31fa0ed0cc5bb60091eb0fdef3edda0c1b1f7ccd9e3479dcb651710c5f893d2e61853ce7242de9e0c953a0",
          "sha256": "8af65907f975892e09a2ab4178518638e6e52cc453d16643947dc2480fb88cd5",
          "sha1": "a653e816179e2eeac21949ca29e306ff508478d6",
          "md5": "002a5062ccd05db580670eb8887df879"
        }
      ]
    }
  ]
}
