{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "QueryViewer",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "QueryViewer-1.1.2.aar",
          "url": "QueryViewer-1.1.2.aar",
          "size": 35462,
          "sha512": "cf95339f5d43f2ac57c04833462190db1610d3f3e0928c67f5f2eca6c715e9b7c19ac34ed9de5b432276f12f289b2a9ad9eaa667fd9653c402f3827d4e76f4ae",
          "sha256": "58261a06cd4d2c0d90e01482c3e0a2051fd99c58ef00c43c304f5662fe16a79c",
          "sha1": "1c69a7130400b24efba61f4c03e65bbfaeb363c5",
          "md5": "5abe0930aefb3d4df32459d8adb51dad"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "QueryViewer-1.1.2.aar",
          "url": "QueryViewer-1.1.2.aar",
          "size": 35462,
          "sha512": "cf95339f5d43f2ac57c04833462190db1610d3f3e0928c67f5f2eca6c715e9b7c19ac34ed9de5b432276f12f289b2a9ad9eaa667fd9653c402f3827d4e76f4ae",
          "sha256": "58261a06cd4d2c0d90e01482c3e0a2051fd99c58ef00c43c304f5662fe16a79c",
          "sha1": "1c69a7130400b24efba61f4c03e65bbfaeb363c5",
          "md5": "5abe0930aefb3d4df32459d8adb51dad"
        }
      ]
    }
  ]
}
