{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "ToggleButton",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ToggleButton-1.1.2.aar",
          "url": "ToggleButton-1.1.2.aar",
          "size": 29493,
          "sha512": "dd7f5028e5d5c007c218d8ba44e5d9d2a2618b7dfdf1dd1f472da9321be64092fa5c2f601da83fc6885692f1300de3f0c8e9f299184aa55c361ff0ebfa198a8d",
          "sha256": "41019ff48df02d28b7df80d80b54a2044a2c37425ea84291bad3272b3d58b97a",
          "sha1": "ff798a31db2eb7cd886c9c2dfd9640b60a7616bf",
          "md5": "121897105e4e33ba89a58e41d9940b74"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "FlexibleClient",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "org.honorato.multistatetogglebutton",
          "module": "multistatetogglebutton",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ToggleButton-1.1.2.aar",
          "url": "ToggleButton-1.1.2.aar",
          "size": 29493,
          "sha512": "dd7f5028e5d5c007c218d8ba44e5d9d2a2618b7dfdf1dd1f472da9321be64092fa5c2f601da83fc6885692f1300de3f0c8e9f299184aa55c361ff0ebfa198a8d",
          "sha256": "41019ff48df02d28b7df80d80b54a2044a2c37425ea84291bad3272b3d58b97a",
          "sha1": "ff798a31db2eb7cd886c9c2dfd9640b60a7616bf",
          "md5": "121897105e4e33ba89a58e41d9940b74"
        }
      ]
    }
  ]
}
